services:
  - type: web
    name: aiassistent
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
